<Project Sdk="Dalamud.NET.Sdk/15.0.0">
 <PropertyGroup>
  <AssemblyName>VieriWrathEngine.PunishLib</AssemblyName>
  <RootNamespace>PunishLib</RootNamespace>
  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  <Use_DalamudPackager>false</Use_DalamudPackager>
 </PropertyGroup>
 <ItemGroup>
  <Reference Include="Dalamud.Common"><HintPath>$(AppData)/XIVLauncher/addon/Hooks/dev/Dalamud.Common.dll</HintPath><Private>false</Private></Reference>
  <Compile Include="../Upstream/PunishLib/**/*.cs" />
  <ProjectReference Include="../Upstream/ECommons/ECommons.csproj" />
 </ItemGroup>
</Project>
